set minimum requirement for jekyll-feed
Since jekyll/jekyll#6137 `baseurl` can be `nil`. Until jekyll-feed 0.8
the `baseurl` has been used as argument to `URI.join`. When `baseurl`
is `nil` this throws an exeption:

> URI.join('http://example.com', nil)
> ArgumentError: bad argument (expected URI object or URI string)

The usage of `baseurl` within jekyll-feed has been removed in
jekyll/jekyll-feed@bf728c321d715f8bb1673e43fb3c848fe736fa6d