Fixes NoMethodError caused by 3241d882b515ceef7accdc3610e74442843be70a
example:
../../deps/jekyll/bin/../lib/jekyll/convertible.rb:81:in `do_layout': undefined method `name' for <Post: ...>:Jekyll::Post (NoMethodError)